# Generated by Django 3.0.7 on 2020-06-22 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=1000)),
                ('objectives', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=256)),
                ('event_type', models.CharField(max_length=256)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_desc', models.CharField(max_length=400)),
                ('reg_link', models.URLField()),
                ('event_poster', models.ImageField(default=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_order', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_date', models.DateTimeField()),
                ('img_src', models.ImageField(default=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resources_indi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('res_link', models.URLField()),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_club_app.Resources')),
            ],
        ),
    ]
