# Generated by Django 3.0.7 on 2020-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_club_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position_order',
            field=models.IntegerField(default=True),
        ),
    ]
