# Generated by Django 3.0.7 on 2020-06-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_club_app', '0004_auto_20200622_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
