# Generated by Django 3.0.7 on 2020-06-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_club_app', '0007_auto_20200623_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
