# Generated by Django 3.0.7 on 2020-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_club_app', '0008_auto_20200623_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='res_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_desc',
            field=models.CharField(default=True, max_length=300),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_img',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_poster',
            field=models.ImageField(default=True, upload_to='event'),
        ),
        migrations.DeleteModel(
            name='Resources_indi',
        ),
    ]
