# Generated by Django 3.0.7 on 2020-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_club_app', '0009_auto_20200624_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_about_us',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about_us', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Home_desc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('head_1', models.CharField(max_length=50)),
                ('head_2', models.CharField(max_length=50)),
            ],
        ),
    ]
