# Generated by Django 3.0.7 on 2020-06-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_club_app', '0010_home_about_us_home_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_pref',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
