# Generated by Django 3.0.7 on 2020-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_club_app', '0011_events_event_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_about_us',
            name='contact_us',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='event_pref',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='Low', max_length=10),
        ),
    ]
