# Generated by Django 3.0.7 on 2020-06-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_club_app', '0012_auto_20200626_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_desc',
            name='img1',
            field=models.ImageField(default=True, upload_to='home_car'),
        ),
        migrations.AddField(
            model_name='home_desc',
            name='img2',
            field=models.ImageField(default=True, upload_to='home_car'),
        ),
        migrations.AddField(
            model_name='home_desc',
            name='img3',
            field=models.ImageField(default=True, upload_to='home_car'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_pref',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
